export enum ReducerActionType {
  USER_STORY = "USER_STORY",
  CURRENT_AVATAR_META_DATA = "CURRENT_AVATAR_META_DATA",
  PREV_AVATAR_META_DATA = "PREV_AVATAR_META_DATA",
  NEXT_AVATAR_META_DATA = "NEXT_AVATAR_META_DATA",
  ENABLE_STORY_VIEW = "ENABLE_STORY_VIEW",
  CURRENT_STORY_INDEX = "CURRENT_STORY_INDEX",
  CURRENT_USER_ID = "CURRENT_USER_ID",
  RESET = "RESET",
  USER_STORIES_LIST = "USER_STORIES_LIST"
}
